# learn routes
mofc_learn_decks:
    path:     /{_locale}/learn/decks
    defaults: { _controller: MoFlashCardsBundle:Learn:decks }

mofc_learn_cards:
    path:     /{_locale}/learn/cards/{deckSlug}
    defaults: { _controller: MoFlashCardsBundle:Learn:cards }