# api routes
_api_cards:
    path:     /api/cards/{group}
    defaults: { _controller: MoFlashCardsBundle:Api:cards }

# learn routes
_learn_cards:
    path:     /{_locale}/learn/cards/{group}
    defaults: { _controller: MoFlashCardsBundle:Learn:cards }
