# api routes
mofc_api_cards:
    path:     /api/cards/{deckSlug}
    defaults: { _controller: MoFlashCardsBundle:Api:cards }

# learn routes
mofc_learn_cards:
    path:     /{_locale}/learn/cards/{deckSlug}
    defaults: { _controller: MoFlashCardsBundle:Learn:cards }
