deck:
    resource: "mofc.api.controller.deck"
    type: rest
    name_prefix: mofc_api_

# custom routes
mofc_api_get_tts:
    path: /text-to-speech/{text}
    defaults: { _controller: mofc.api.controller.resource:textToSpeechAction }
    methods: [GET]
