flash_cards_api:
    resource: "@MoFlashCardsApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

flash_cards:
    resource: "@MoFlashCardsBundle/Resources/config/routing.yml"
    prefix: /
    requirements:
        _locale: en|bg
    
logout:
    path: /logout
