_flash_cards:
    resource: "@MoFlashCardsBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _locale: en|bg

_app:
    resource: @AppBundle/Controller/
    type:     annotation
