flash_cards_api:
    resource: "@MoFlashCardsApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

flash_cards:
    resource: "@MoFlashCardsBundle/Resources/config/routing.yml"
    prefix: /
    requirements:
        _locale: en|bg

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
logout:
    path: /logout
