api:
    resource: "@MoFlashCardsApiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

mo_flash_cards:
    resource: "@MoFlashCardsBundle/Resources/config/routing.yml"
    prefix: /
    requirements:
        _locale: en|bg

app:
    resource: @AppBundle/Controller/
    type: annotation
    
logout:
    path: /logout
