deck_list:
    path:     /api/decks
    defaults: { _controller: DeckBundle:Deck:list }
    methods:  [GET]
    
deck_get:
    path:     /api/decks/{slug}
    defaults: { _controller: DeckBundle:Deck:get }
    methods:  [GET]
    